module.exports = [
  "Beautiful place",
  "One of the most beautiful views.",
  "Incredible wild trail and one of the best parts of San Francisco.",
  "Beautiful views! Caught a gorgeous sunset towards the end of the hike. Includes some challenging stairs and climbing that could be an issue for some. Trail was a little crowded and loud at times, but the views were so worth it.",
  "easy hike with great views!",
  "Awesome views of the ocean and golden gate. Downside is how much foot traffic there is.",
  "Fun and easy hike. Gets crowded on Saturday especially when the weather is nice. Will do it again since it is just minutes away from my home.",
  "So fortunate to have caught it on a clear day. Easily one of the most beautiful urban hikes I have seen. Parking was a breeze at the visitors center.",
  "I remember hiking here 40 years ago ... only tiny dirt trails. How time changes. Beautiful nevertheless",
  "One of my favorite trails in the city and a major reason why I love living here. The views are stunning. Well worth the effort.",
  "Easy loop, great view, best to go on a weekday though if you can.",
  "We got to hike the trail at sunset and got some amazing pictures. The view was worth every step!",
  "Sickest Time I ever had in my life, I wanna burst",
  "I lost my watch but it really did not bother me at all.  I was lost in the beauty",
  "I proposed but she laughed in my face.  It is all good though, there was a bar nearby",
  "PM me and I will give you the sickest mixtape ever to run here with.  Do they even say mixtape anymore?  Does not  matter.  You will love it, I swear",
  "I feel like I am on top of the world when I am here...even though I am at sea level....but who is really keeping track of the elevation, except me. I guess I am the only one.  I need to get out more.  Ping me if anyone wants to hang out, I ampretty much always avaialable.",
  "Reminds me of that place in Barcelona.  The place with all the sunshine.",
  "Hole in the wall coffee a good mid-trail break with a end of trail bread chowder bowl at Nicks a bonus",
  "7 AM on a Saturday. Nice and quiet. Hope to enjoy the sights at a walking pace later.",
  "Picturesque trail thru Chinatown past pier 39. Easy trail to follow with the medallions in sidewalk. 3hrs including some shopping and a stop at the beach.",
  "Mostly paved, along roads. Starts strong, with views and wooded paths, but peters out quickly",
  "Great for an easy city trek!",
  "Nice walk in the woods.",
  "It was pretty and an easy urban hike.",
  "Yes, a lovely area. I used to play volleyball near it. On the edge of the green."
];
